Article/urls.py
from django.contrib import admin
from django.urls import path
from Article import views
app_name = 'Article'
urlpatterns = [
   
    path('', views.articles,name='articles'),
    path('article/<int:id>', views.article,name='article'),
    path('myarticles/', views.myarticles,name='myarticles'),
    path('update/<int:id>', views.updateArticle,name='update'),
    path('delete/<int:id>', views.deleteArticle,name='delete'),
    path('comment/<int:id>', views.comment,name='comment'),
    path('comments/<int:id>', views.comments,name='comments'),
]

Post/urls.py
from django.contrib import admin
from django.urls import path,include
from Article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page,name="anasayfa"),
    path('about/', views.about,name='about'),
    path('articles/', include("Article.urls")),
    path('user/', include("user.urls")),
]

user/urls.py
from django.contrib import admin
from django.urls import path,include
from user import views
app_name = "user"
urlpatterns = [
    path('register/',views.register,name = 'register'),
    path('login/',views.loginUser,name = 'login'),
    path('logout/',views.logoutUser,name = 'logout'),
    path('addarticle/',views.addArticle,name = 'addarticle'),
]

Article/models.py
from django.db import models

class Article(models.Model):
    author = models.ForeignKey('auth.User',max_length=100,on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Point(models.Model):
    point = models.CharField(max_length=10)
    def __str__(self):
        return self.point


class Rating(models.Model):
    title = models.CharField(max_length=100)
    point = models.ForeignKey(Point,on_delete=models.CASCADE)
    exp = models.TextField(blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.point

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from Article.models import Article
from Article.models import Rating
class LoginForm(forms.Form):
    username = forms.CharField(max_length=50,label='Kullanıcı Adı')
    password = forms.CharField(max_length=50,label='Parola',widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50,label='Kullanıcı Adı')
    password = forms.CharField(max_length=20,label='Parola',widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label='Parolayı Doğrula',widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")
        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolalar Eşleşmiyor.")
        values = {
            "username":username,
            "password":password       }
        return values
    
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title','content']   


class commentForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ['point','exp']

Article/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Article,Rating
from user.forms import ArticleForm,commentForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
def home_page(request):
    return render(request,'home_page.html')
def about(request):
    return render(request,'about.html')
def articles(request):
    articles = Article.objects.all()
    context = dict(
        articles = articles
    )
    return render(request,'articles.html',context)

def article(request,id):
    # article = Article.objects.get(id=id)
    article = get_object_or_404(Article,id=id)
    context = dict(
        article = article
    )
    return render(request,'article.html',context)
@login_required
def myarticles(request):
    articles = Article.objects.filter(author = request.user)
    context = dict(
        articles = articles
    )
    return render(request,'myarticles.html',context)
@login_required
def updateArticle(request,id):
    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,instance=article)
    context = dict(
        form = form
    )
    if form.is_valid():
        newarticle = form.save(commit=False)
        newarticle.author = request.user
        newarticle.save()
        messages.success(request,'Makale Başarıyla Güncellendi.')
        return redirect('anasayfa')
    return render(request,'update.html',context)
@login_required
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)
    article.delete()
    messages.success(request,'Makale başarıyla silindi.')
    return redirect('anasayfa')


def comment(request,id):
    
    form = commentForm(request.POST or None)
    article = get_object_or_404(Article,id = id)
    context = dict(
        form = form
    )
    if form.is_valid():
        comment = form.save(commit=False)
        comment.title = article.title
        comment.save()
        messages.success(request,'Yorum Başarıyla Eklendi.')
        return redirect('anasayfa')

    return render(request,'comment.html',context)


def comments(request,id):
    article = get_object_or_404(Article,id = id)
    comment = Rating.objects.filter(title = article.title)
    context = dict(
        comment = comment
    )
    return render(request,'comments.html',context)

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm
def register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
       username = form.cleaned_data.get("username")  
       password = form.cleaned_data.get("password")


       newUser = User(username = username)
       newUser.set_password(password)
       newUser.save()
       login(request,newUser)
       messages.success(request,'Başarıyla Kayıt Olundu')
       return redirect("anasayfa")

    context = {
        "form":form
    }  
    return render(request,'register.html',context)
   
def loginUser(request):
    form = LoginForm(request.POST or None)
    context = {
        'form':form
    }
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username = username, password = password)
        if user is None:
            messages.info(request,'Kullanıcı Adı veya Parola Hatalı')
            return render(request,'login.html',context)
        messages.success(request,'Başarıyla Giriş Yaptınız.')
        login(request,user)
        return redirect('anasayfa')
    return render(request,'login.html',context)
@login_required
def logoutUser(request):
    logout(request)
    messages.success(request,'Başarıyla çıkış yaptınız.')
    return redirect('anasayfa')
@login_required
def addArticle(request):
    form = ArticleForm(request.POST or None)
    context = dict(
        form = form
    )
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,'Makale Başarıyla Eklendi')
        return redirect('anasayfa')
    return render(request,'addarticle.html',context)

templates/about.html
{% extends 'layout.html' %}

{% block container %}

<h2 style="margin-top: 40px;margin-left: 20px;">Hakkımızda</h2>
<hr>


{% endblock  %}

templates/addarticle.html
{% extends 'layout.html' %}

{% block container %}

<h2 style="margin-top: 40px;margin-left: 20px;">Makale Ekle</h2>
<hr>
<form method="post" action="">
    {% csrf_token %}
    {{form.as_p}}
    <button type = "submit" value = "Submit" class = "btn btn-danger">Ekle</button>
</form>


{% endblock  %}

templates/article.html
{% extends 'layout.html' %}
{% block container  %}

<h1 style="margin-top: 40px;margin-left: 20px;">Başlık:{{article.title}}</h1>
<hr>
<h3>Yazar:{{article.author}}</h3> 
<hr>
<p>Content:{{article.content}}</p>   
<hr>


{% endblock  %}

templates/articles.html
{% extends 'layout.html'  %}



{% block container %}

<h2 style="margin-top: 40px;margin-left: 20px;">Makaleler</h2>
<hr>
{% if articles  %}
<table class="table">
  <thead>
    <tr>
      
      <th scope="col">İd</th>
      <th scope="col">Author</th>
      <th scope="col">Title</th>
      <th scope="col">Created_At</th>
      <th scope="col">Comment</th>
      <th scope="col">Assecations</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      {% for article in articles %}
      
      <th scope="row"><a href="{% url 'Article:article' article.id  %}" style="color: black;">{{article.id}}</a></th>
      <td><a href="{% url 'Article:article' article.id  %}" style="color: black;">{{article.author}}</a></td>
      <td><a href="{% url 'Article:article' article.id   %}" style="color: black;">{{article.title}}</a></td>
      <td><a href="{% url 'Article:article' article.id   %}" style="color: black;">{{article.created_at}}</a></td>
      <td><a class="btn btn-danger" href="{% url 'Article:comment' article.id %}">Yorumla</a></td>
      <td><a class="btn btn-danger" href="{% url 'Article:comments' article.id %}">Yorumlamaları Göster</a></td>
      
    </tr>
    {% endfor %}
  </tbody>
</table>
<br>
<a href="{% url 'user:addarticle' %}"class = "btn btn-danger" >Makale Ekle</a>
{% endif %}
{% endblock  %}

templates/comment.html
{% extends 'layout.html' %}

{% block container %}

<h2 style="margin-top: 40px;margin-left: 20px;">Makale Yorum Ekle</h2>
<hr>
<form method="post" action="">
    {% csrf_token %}
    {{form.as_p}}
    <button type = "submit" value = "Submit" class = "btn btn-danger">Ekle</button>
</form>


{% endblock  %}

templates/comments.html
{% extends 'layout.html' %}

{% block container %}
<h2 style="margin-top: 40px;margin-left: 20px;">Yorumlar</h2>
<hr>
{% if comment  %}
   
  {% for article in comment %}
  <h3>{{article.eser}}</h3>
    <div class="div" style="padding: 10px ; border: solid black 5px;background-color: #707070;margin-top: 1px;display: block;position: relative;">
    <h2 style=" text-decoration: none;color:aliceblue;">{{article.point}}</h2>
    <p style=" text-decoration: none;color:aliceblue;">{{article.exp}}</p>
    <p>{{article.created_at}}</p>
</div>

  {% endfor   %}

{% endif %}



{% endblock %}

templates/home_page.html
{% extends 'layout.html' %}
{% block container  %}

<h2 style="margin-top: 40px;margin-left: 20px;">AnaSayfa</h1>
<hr>
<p>
    {% if request.user.is_authenticated %}

Giriş Yapılmış,{{request.user.username}}

    {% else %}
Giriş Yapılmamış

    {% endif %}
</p>
{% endblock  %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <a class="navbar-brand" href="/">YBBlog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about' %}">Hakkımızda <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'Article:articles' %}">Makaleler</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'Article:myarticles' %}">Makalelerim</a>
        </li>
      </ul>
      <ul class = 'navbar-nav ml-auto'>
        {% if request.user.is_authenticated %}
        
          
      
      {% else  %}
      <li class = 'nav-item active'>
        <a class = 'nav-link' href="/user/login">Giriş Yap</a>
    </li>
    <li class = 'nav-item active'>
      <a class = 'nav-link' href="/user/register">Kayıt Ol</a>
  </li>
    
      {% endif %}
       
        <li class = 'nav-item active'>
            <a class = 'nav-link' href="/user/logout">Çıkış Yap</a>
        </li>
      </ul>
      
    </div>
  </nav>

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Hızlı Exercise</title>
</head>
<body>
    {% include 'includes/navbar.html' %}  
    {% if messages %}
      
       {% for message in messages %}
        {% if message.tags == 'info' %}
        <div{% if message.tags %} class="alert alert-danger"{% endif %}>{{ message }}</div>
        {% else %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endif %}
       {% endfor %}
      
    {% endif %}
    {% block container %}


  {% endblock  %}
    




<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block container %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2>Giriş Yap</h2>
<hr>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type = "submit" value = "Submit" class = "btn btn-danger">Giriş Yap</button>
</form>
    </div>
  </div>


{% endblock  %}

templates/myarticles.html
{% extends 'layout.html' %}

{% block container %}
<h2 style="margin-top: 40px;margin-left: 20px;">Makalelerim</h2>
<hr>
{% if articles  %}

  {% for article in articles %}
    <div class="div" style="padding: 10px ; border: solid black 5px;background-color: #707070;margin-top: 1px;display: block;position: relative;">
    <a href="{% url 'Article:article' article.id %}" style=" text-decoration: none;color:aliceblue;">{{article.title}}</a>
    <div class="right"  style = "position: absolute; right: 2px; top: 6px;">
    <a class = "btn btn-danger" href="{% url 'Article:update' article.id %}">Düzenle</a>
    <a class = "btn btn-danger" href="{% url 'Article:delete' article.id %}">Sil</a>
  </div>
</div>

  {% endfor   %}

{% endif %}


<a href="{% url 'user:addarticle' %}"class = "btn btn-danger" >Makale Ekle</a>
{% endblock %}

templates/register.html
{% extends 'layout.html' %}
{% block container %}

<h2>Kayıt Ol</h2>
<hr>
<form method="post" action="">
    {% csrf_token %}
    {{form.as_p}}
    <button type = "submit" value = "Submit" class = "btn btn-danger">Kayıt Ol</button>
</form>



{% endblock  %}

templates/update.html
{% extends 'layout.html' %}

{% block container %}
<h2 style="margin-top: 40px;margin-left: 20px;">Makale Güncelle</h2>
<hr>
<form method="post" action="">
    {% csrf_token %}
    {{form.as_p}}
    <button type = "submit" value = "Submit" class = "btn btn-danger">Güncelle</button>
</form>



{% endblock  %}